import { FontSize, Color, Border, Padding } from "./GlobalStyles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  tituloPosition: {
    height: '20%',
    width: '100%',
    position: "absolute",
    },
    buttonTextMenu: {
      color: "white",
      textAlign: "center",
    },
  buttonMenu: {
      flex: 1,
      marginHorizontal: 5,
      alignSelf: "stretch",
      alignItems: "center",
    },
  containerMenu: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#10294F",
      borderRadius: 15,
      paddingVertical: 15,
      paddingHorizontal: 10,
      top: "53%",
      width: "90%",
      left: -25,
      height: 70, // Ajusta el ancho según tus necesidades
      maxWidth: 500, // Establece un ancho máximo si lo deseas
      alignSelf: "center", // Centra el rectángulo horizontalmente
      marginVertical: 30, // Espaciado vertical si es necesario
    },
    eyeiconLayout: {
      maxHeight: "100%",
      position: "absolute",
    },
    cardLayout: {
      height: '100%',
      width: '100%',
      position: "absolute",
    },
    gradient: {
      flex: 1,
      width: "100%",
      height: "100%",
      overflow: "hidden",
      backgroundColor: "transparent",

    },
    scrollLayout: {
      top: 50,
      width: "100%",
    },
    datosLayout2: {
      height: 336,
      width: 312,
      left: 0,
      top: 0,
    },
    appbarShadowBox: {
      shadowOpacity: 1,
      elevation: 10,
      shadowRadius: 10,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowColor: "rgba(0, 0, 0, 0.25)",
    },
    tablaLayout4: {
      height: 180,
      width: 206,
      position: "absolute",
    },
    tablaChildLayout1: {
      borderRadius: Border.br_3xs,
      top: 0,
    },
    tablaLayout3: {
      height: 16,
      backgroundColor: Color.colorMistyrose,
      width: 206,
      left: 0,
      position: "absolute",
    },
    tablaChildLayout: {
      backgroundColor: Color.colorMistyrose,
      height: 15,
      width: 206,
      left: 0,
      position: "absolute",
    },
    datosLayout1: {
      height: 177,
      position: "absolute",
    },
    minTypo: {
      color: Color.colorBlack,
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
    },
    itemPosition: {
      top: 15,
      left: 0,
      position: "absolute",
    },
    tablaLayout2: {
      height: 110,
      width: 289,
      left: "50%",
      position: "absolute",
    },
    tablaLayout1: {
      width: 288,
      height: 14,
      backgroundColor: Color.colorMistyrose,
      left: 0,
      position: "absolute",
    },
    datosLayout: {
      height: 105,
      position: "absolute",
    },
    text9Position: {
      top: 14,
      left: 0,
      position: "absolute",
    },
    tablaLayout: {
      height: 219,
      width: 312,
      left: 0,
      position: "absolute",
    },
    cr2Typo: {
      fontSize: FontSize.size_sm,
      color: Color.colorBlack,
      lineHeight: 15,
      textAlign: "center",
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      position: "absolute",
    },
    sonometroLayout: {
      height: 178,
      width: 186,
      position: "absolute",
    },
    childLayout: {
      marginLeft: -93,
      height: 179,
      width: 186,
    },
    textTypo: {
      marginLeft: -16.5,
      fontSize: FontSize.size_sm,
      color: Color.colorBlack,
      lineHeight: 15,
      textAlign: "center",
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      left: "50%",
      position: "absolute",
    },
    itemLayout: {
      height: 46,
      width: 1,
      borderRightWidth: 1,
      borderColor: Color.colorBlack,
      borderStyle: "solid",
      marginLeft: -1.5,
    },
    min2Typo: {
      top: 122,
      fontSize: FontSize.size_sm,
      color: Color.colorBlack,
      lineHeight: 15,
      textAlign: "center",
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      position: "absolute",
    },
    temPosition: {
      top: 26,
      left: "50%",
      position: "absolute",
    },
    appbarChildLayout: {
      height: 60,
      position: "absolute",
    },
    opcionPosition: {
      bottom: "0%",
      top: "0%",
      height: "100%",
    },
    informeTypo: {
      textAlign: "left",
      fontSize: FontSize.size_xs,
    },
    opcionChildPosition: {
      backgroundColor: Color.colorGainsboro,
      height: 60,
      left: 0,
      top: 0,
      position: "absolute",
    },
    tituloChild: {
      backgroundColor: "transparent",
    },
    safearea: {
      height: 2000,
      flex: 1,
    },
    eyeicon: {
      marginLeft: -32.5,
      width: 143,
      bottom: "0%",
      top: "0%",
      height: "100%",
      left: "50%",
      opacity:0.08,
    },
    global: {
      marginLeft: -110.5,
      fontSize: 30,
      textAlign: "center",
      color: Color.colorWhite,
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      top: 20,
      left: "50%",
      position: "absolute",
    },
    encabezado: {
      height: "45.45%",
      marginLeft: -49,
      top: "6.42%",
      bottom: "48.13%",
      width: 221,
      left: "50%",
      position: "absolute",
    },
    cardChild: {
      borderTopLeftRadius: Border.br_31xl,
      borderTopRightRadius: Border.br_31xl,
      top: 0,
      backgroundColor: Color.colorGhostwhite_100,
    },
    card: {
      top: 110,
    },
    datosMaquinaChild: {
      backgroundColor: Color.colorWhite,
      elevation: 10,
      shadowRadius: 10,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowColor: "rgba(0, 0, 0, 0.25)",
      borderRadius: Border.br_xl,
      position: "absolute",
      height: 336,
      width: 312,
      left: 0,
      top: 0,
    },
    tablaDatosChild: {
      backgroundColor: "#eef0f8",
      height: 180,
      width: 206,
      position: "absolute",
      left: 0,
    },
    tablaDatosItem: {
      top: 165,
      borderBottomRightRadius: Border.br_3xs,
      borderBottomLeftRadius: Border.br_3xs,
      backgroundColor: "#f4dd83",
      height: 15,
      width: 206,
      left: 0,
      position: "absolute",
    },
    tablaDatosInner: {
      top: 148,
    },
    rectangleView: {
      top: 117,
      height: 14,
      backgroundColor: Color.colorMistyrose,
      width: 206,
      left: 0,
      position: "absolute",
    },
    tablaDatosChild1: {
      top: 84,
    },
    tablaDatosChild2: {
      top: 51,
    },
    tablaDatosChild3: {
      top: 19,
    },
    mquina: {
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      top: 0,
      position: "absolute",
    },
    estado: {
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      top: 16,
      left: 0,
      position: "absolute",
    },
    velocidad: {
      top: 32,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    velocidadMax: {
      top: 48,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    cantidad: {
      top: 64,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    cantidadXMin: {
      top: 80,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    inicio: {
      top: 96,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    ultimoStatus: {
      top: 112,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    tiempoActiva: {
      top: 128,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    disponibilidad: {
      top: 144,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    p: {
      top: 160,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    nombreDatos: {
      top: 1,
      left: 7,
      width: 100,
      height: 175,
      position: "absolute",
    },
    kw: {
      top: 162,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text: {
      top: 114,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    min: {
      top: 130,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text1: {
      top: 145,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    detenida: {
      top: 18,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text2: {
      top: 33,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text3: {
      top: 49,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text4: {
      top: 66,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text5: {
      top: 82,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text6: {
      top: 98,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    resultadoDatos: {
      left: 125,
      width: 130,
      top: 0,
    },
    lineIcon: {
      height: 147,
      width: 206,
    },
    datos: {
      top: 3,
      width: 206,
      left: 0,
    },
    tablaDatos: {
      left: 91,
      top: 16,
    },
    tablaDatos2Child: {
      marginLeft: -144.5,
      borderRadius: Border.br_3xs,
      top: 0,
      backgroundColor: Color.colorGhostwhite_100,
    },
    tablaDatos2Item: {
      top: 20,
      width: 288,
    },
    tablaDatos2Inner: {
      top: 50,
    },
    tablaDatos2Child1: {
      top: 80,
    },
    item: {
      color: Color.colorBlack,
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      textAlign: "center",
    },
    cliente: {
      top: 30,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    sp: {
      top: 45,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    cantSolicitada: {
      top: 60,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    cantFabricada: {
      top: 75,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    cantUltIngreso: {
      top: 90,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    nombreDatos2: {
      left: 6,
      width: 126,
      top: 0,
    },
    text7: {
      top: 44,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text8: {
      top: 29,
      lineHeight: 15,
      fontSize: FontSize.size_3xs,
      color: Color.colorBlack,
      textAlign: "center",
      left: 0,
      position: "absolute",
    },
    text9: {
      color: Color.colorBlack,
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      lineHeight: 15,
      fontSize: 9,
      textAlign: "center",
    },
    resultadoDatos2: {
      left: 130,
      width: 200,
      top: 0,
    },
    lineIcon1: {
      height: 76,
      width: 289,
    },
    datos2: {
      top: 5,
      width: 289,
      left: 0,
    },
    tablaDatos2: {
      marginLeft: -145,
      top: 215,
    },
    datosMaquina: {
    },
    tablaChildShadowBox: {
      height: 171,
      shadowOpacity: 1,
      elevation: 10,
      shadowRadius: 10,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowColor: "rgba(0, 0, 0, 0.25)",
      backgroundColor: Color.colorWhite,
      borderRadius: Border.br_xl,
      width: 312,
      left: 0,
      top: 0,
      position: "absolute",
    },
    sonmetroDb: {
      marginLeft: -57,
      top: 11,
      left: "52%",
    },
    min1: {
      left: 1,
      top: 96,
    },
    max: {
      left: 157,
      top: 96,
    },
    min2: {
      left: 1,
      top: 96,
    },
    max2: {
      left: 157,
      top: 96,
    },
    sonometroChild: {
      left: "50%",
      top: 0,
      position: "absolute",
    },
    temp1Child: {
      left: "50%",
      top: 25,
      position: "absolute",
    },
    text14: {
      textAlign: "center",
      top: 108,
    },
    sonometroItem: {
      left: "50%",
      top: 0,
      position: "absolute",
    },
    sonometro: {
      top: 41,
      left: 64,
      height: 178,
    },
    tablaSonometro: {
      top: 350,
    },
    min2: {
      left: 1,
    },
    max1: {
      left: 157,
    },
    temSolubleCChild: {
      marginLeft: -93,
      height: 178,
      width: 186,
    },
    text15: {
      top: 136,
    },
    temSolubleCItem: {
      height: 46,
      width: 1,
      borderRightWidth: 1,
      borderColor: Color.colorBlack,
      borderStyle: "solid",
      marginLeft: -1.5,
    },
    cr2Tem: {
      marginLeft: -85,
      left: "58%",
      top: 0,
    },
    temSolubleC: {
      height: 204,
      width: 186,
      left: 64,
      top: 15,
      position: "absolute",
    },
    tablaTemSolubleC: {
      top: 538,
    },
    temTinaEnfriamientoC: {
      left: 65,
      top: 44,
    },
    cr2Tem1: {
      marginLeft: -100,
      top: 18,
      left: 155,
      
    },
    tablaTemTinaEnfriamiento: {
      top: -335,
      height: 222,
      left: 0,
    },
    image1Icon: {
      top: 21,
      width: 77,
      height: 172,
      left: 5,
      position: "absolute",
    },
    scroll: {
      top: 222,
      height: 1130,
      marginLeft: -156,
      left: "50%",
      width: "100%",
    },

    scrollView: {
      top: "-38%",
      flex: 1,
    },
    appbarChild: {
      backgroundColor: "#122a4e",
      width: 350,
      height: 60,
      borderRadius: Border.br_xl,
      left: 0,
      top: 0,
      opacity: 0.00
    },
    opcionGlobalChild: {
      borderTopLeftRadius: Border.br_xl,
      borderBottomLeftRadius: Border.br_xl,
      backgroundColor: "#2d4e80",
      width: 110,
      left: 0,
      top: 0,
      opacity: 0.00
    },
    eyeicon1: {
      height: "26.67%",
      marginLeft: -15.51,
      top: "25%",
      bottom: "48.33%",
      width: 22,
      left: "50%",
    },
    global1: {
      marginLeft: -23.97,
      top: 35,
      fontWeight: "800",
      //fontFamily: FontFamily.interExtraBold,
      width: 45,
      fontSize: FontSize.size_xs,
      textAlign: "center",
      color: Color.colorWhite,
      left: "50%",
      position: "absolute",
      opacity: 0.00
    },
    opcionGlobal: {
      width: 110,
      left: 0,
      top: 0,
      opacity: 0.00
    },
    fileicon: {
      height: "45%",
      top: "13.33%",
      right: 56,
      bottom: "41.67%",
      width: 18,
    },
    informe: {
      left: 43,
      width: 45,
      //fontFamily: FontFamily.interRegular,
      top: 37,
      textAlign: "left",
      height: 16,
      color: Color.colorWhite,
      position: "absolute",
    },
    opcionInformeChild: {
      width: 130,
    },
    opcionInforme: {
      right: 110,
      width: 130,
      position: "absolute",
      opacity: 0.00
    },
    cogicon: {
      height: "33.33%",
      width: "18.56%",
      top: "21.67%",
      right: "40.53%",
      bottom: "45%",
      left: "40.91%",
      maxWidth: "100%",
      overflow: "hidden",
    },
    ajustes: {
      left: 34,
      width: 42,
      //fontFamily: FontFamily.interRegular,
      top: 37,
      textAlign: "left",
      height: 16,
      color: Color.colorWhite,
      position: "absolute",
    },
    opcionAjustesChild: {
      borderTopRightRadius: Border.br_xl,
      borderBottomRightRadius: Border.br_xl,
      width: 110,
    },
    opcionAjustes: {
      width: "31.43%",
      right: "0%",
      left: "68.57%",
      position: "absolute",
      opacity: 0.00
    },
    appbar: {
      top: '30.5%', // Ajusta este valor según tus necesidades
      width: '100%',
      left: '7.3%',
      height: '10%', // Ajusta este valor según tus necesidades
      alignSelf: 'center',
    },
  
    vectorIcon: {
      width: 16,
      height: 13,
    },
    mquinaCr2: {
      width: 108,
      height: 20,
      marginLeft: 61,
      color: Color.colorBlack,
      //fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
    },
    vectorIcon1: {
      width: 17,
      height: 9,
      marginLeft: 61,
    },
    selecopcionlight: {
      top: 145,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Padding.p_5xl,
      paddingVertical: Padding.p_smi,
      backgroundColor: Color.colorWhite,
      elevation: 10,
      shadowRadius: 10,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowColor: 'rgba(0, 0, 0, 0.25)',
      borderRadius: Border.br_xl,
      position: 'absolute',
      marginLeft: -156,
      left: '50%',
      width: 312, // Añade esta línea
    },
    
    container: {
      flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    },
    selectedText: {
      flex: 1,
    },
    
    loadingIndicator: {
      marginRight: 10,
      right: "37%",
      marginTop: -1190, // Ajusta este valor según tu preferencia para la posición horizontal
    },
    
    globalscreenlight: {
      width: "100%",
      height: 1300,
      overflow: "hidden",
      backgroundColor: Color.colorGhostwhite_100,
    },
});

export const pickerSelectStyles = StyleSheet.create({
  // Estilos específicos para el picker
  // Puedes ajustar el color, tamaño del texto, etc. según tus necesidades
  inputIOS: {
    color: 'black',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 0,
    borderRadius: 8,
    paddingRight: 10,
    width: 300, // Añade esta línea
    textAlign: 'center', // Añade esta línea
},
inputAndroid: {
    color: 'black',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 0,
    borderRadius: 8,
    paddingRight: 10,
    width: 300, // Añade esta línea
    textAlign: 'center', // Añade esta línea
},
});